name: flutter_web_app
description: A flutter web-app demo.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dart.dev packages
  http: ^0.12.2
  path: ^1.7.0
  crypto: ^2.1.5
  built_value: ^7.1.0
  yaml: ^2.2.1
  collection: ^1.14.13
  characters: ^1.0.0
  basics: ^0.4.0+1
  async: ^2.4.2
  typed_data: ^1.2.0
  html: ^0.14.0+3
  meta: ^1.2.2
  mime: ^0.9.6+3
  retry: ^3.0.1
  pem: ^1.0.1
  json_serializable: ^3.3.0
  logging: ^0.11.4
  webcrypto: ^0.1.0
  # markdown: ^2.1.8

  # Flutter.dev packages
  charts_flutter: ^0.9.0
  animations: ^1.1.2
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  video_player: ^0.10.11+2
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+4
  webview_flutter: ^0.3.22+1
  flutter_markdown: ^0.4.3
  flutter_highlight: ^0.6.0

  # Third party packages
  rxdart: ^0.24.1
  provider: ^4.3.1
  flutter_riverpod: ^0.5.1
  retrofit: 1.3.4
  dartx: ^0.5.0
  petitparser: ^3.1.0
  xml: ^4.3.0
  flutter_linkify: ^3.1.3
  timeline_tile: ^0.1.2
  dotted_border: ^1.0.6
  flutter_spinkit: ^4.1.2
  lottie: ^0.5.1
  flutter_svg: ^0.18.0
  location: ^3.0.2
  color: ^2.1.1
  native_color_picker: ^1.0.1
  file_picker: ^1.13.0+1
  file_access: ^1.0.3
  pdf: ^1.10.0
  printing: ^3.5.0
  rsocket: ^0.1.0
  # basic_utils: ^2.6.0
  # logger: ^0.9.2
  # dart_extensions: ^1.0.1
  # easy_web_view: ^1.3.0
  pointycastle:
    git:
      url: git://github.com/bcgit/pc-dart.git


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.0.0
  mockito: ^4.1.1
  retrofit_generator: ^1.3.7+5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
